name: publish
on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install
        if: github.event.pull_request.merged == true
        run: yarn install

      - name: Build
        if: github.event.pull_request.merged == true
        run: yarn nx run-many --target=build

      - name: Publish
        if: github.event.pull_request.merged == true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          yarn lerna publish from-package --yes
